# Generated by Django 5.2.8 on 2026-02-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='project_progress',
            field=models.IntegerField(default=0),
        ),
    ]
